version: '3.8'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword
      - MYSQL_DATABASE=gvu_databases
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
      - ./src/setup_scripts:/school.sql
volumes:
  mysql_data:
  mysql_config: