version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gvu_databases
    ports:
      - "3307:3306"
    volumes:
      - ./src/setup_scripts:/school.sql